version: '2'
services:
    test0403js-app:
        image: test0403js
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://test0403js-mysql:3306/test0403js?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=test0403js-elasticsearch:9300
        ports:
            - 8080:8080
    test0403js-mysql:
        extends:
            file: mysql.yml
            service: test0403js-mysql
    test0403js-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: test0403js-elasticsearch
